version: '3.7'

networks:
  tracoor-net:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  minio-data:
    driver: local


services:
  server:
    image: 'tracoor:latest'
    build:
      context: .
      dockerfile: Dockerfile
    command: single --single-config /etc/config.yaml
    ports:
      - '8081:8081'
      - '9091:9091'
      - '7007:7007'
    volumes:
      - ./single.yaml:/etc/config.yaml
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - tracoor-net
