server:
  addr: ":8081"
  metricsAddr: ":9091"
  gatewayAddr: ":7007"
  pprofAddr: ":6060"
  preStopSleepSeconds: 1
  ntpServer: time.google.com

  persistence:
    dsn: "file:/tmp/tracoor.db"
    driver_name: sqlite

  services:
    indexer:
      retention:
        beaconStates: 30m
        executionBlockTraces: 30m
        beaconBlocks: 30m

agents:
  - name: instance-1
    ethereum:
      overrideNetworkName: mainnet
      beacon:
        nodeAddress: http://instance-1:5052
      execution:
        nodeAddress: http://instance-1:8545
shared:
  metricsAddr: ":9091"
  logging: "debug"
  indexer:
    address: localhost:8081
  store:
    type: fs
    config:
      base_path: "/tmp/tracoor"
