server:
  addr: ":8081"
  gatewayAddr: ":7007"
  pprofAddr: ":6060"
  preStopSleepSeconds: 1
  ntpServer: time.google.com

  persistence:
    dsn: "file:/tmp/tracoor.db"
    driver_name: sqlite

  services:
    indexer:
      retention:
        beaconStates: 30m
        executionBlockTraces: 30m
        beaconBlocks: 30m
  # Use the following to configure Tracoor for a custom network
  # ethereum:
  #   config:
  #     repository: ethpandaops/devnet-repo
  #     branch: master
  #     path: network-configs/devnet-name/metadata
  #   tools:
  #     ncli:
  #       repository: status-im/nimbus-eth2
  #       branch: unstable
  #     lcli:
  #       repository: sigp/lighthouse
  #       branch: unstable
  #     zcli:
  #       fork: consensus-fork-name

agents:
  - name: instance-1
    ethereum:
      overrideNetworkName: mainnet
      # features:
      #   fetchBeaconState: true
      #   fetchBeaconBlock: true
      #   fetchBeaconBadBlock: true
      #   fetchBeaconBadBlob: true
      #   fetchExecutionBlockTrace: true
      #   fetchExecutionBadBlock: true
      beacon:
        nodeAddress: http://instance-1:5052
        # Prysm
        # requires --save-invalid-block-temp and --save-invalid-blob-temp flags enabled
        # Always stored in os.tmpdir(), eg. /tmp
        # invalidGossipVerifiedBlocksPath: /tmp
        # invalidGossipVerifiedBlobsPath: /tmp

        # Nimbus
        # requires --dump flag enabled
        # replace data-dir with the --data-dir flag value
        # invalidGossipVerifiedBlocksPath: /data-dir/dump/invalid

        # Lighthouse
        # requires --invalid-gossip-verified-blocks-path flag set eg. =/data/invalid
        # invalidGossipVerifiedBlocksPath: /data/invalid
      execution:
        nodeAddress: http://instance-1:8545
        traceDisableMemory: true
        traceDisableStack: true
        traceDisableStorage: true

shared:
  metricsAddr: ":9091"
  logging: "debug"
  indexer:
    address: localhost:8081
  store:
    type: fs
    config:
      base_path: "/tmp/tracoor"


ethpandaops/tracoor:0.0.20-debian