type: google.api.Service
config_version: 3

http:
  rules:
    - selector: api.API.ListBeaconState
      post: /v1/api/list-beacon-state
      body: "*"
    - selector: api.API.ListUniqueBeaconStateValues
      post: /v1/api/list-unique-beacon-state-values
      body: "*"
    - selector: api.API.ListExecutionBlockTrace
      post: /v1/api/list-execution-block-trace
      body: "*"
    - selector: api.API.ListUniqueExecutionBlockTraceValues
      post: /v1/api/list-unique-execution-block-trace-values
      body: "*"