type: google.api.Service
config_version: 3

http:
  rules:
    - selector: api.API.GetConfig
      post: /v1/api/get-config
      body: "*"

    - selector: api.API.ListBeaconState
      post: /v1/api/list-beacon-state
      body: "*"
    - selector: api.API.ListUniqueBeaconStateValues
      post: /v1/api/list-unique-beacon-state-values
      body: "*"
    - selector: api.API.CountBeaconState
      post: /v1/api/count-beacon-state
      body: "*"

    - selector: api.API.ListBeaconBlock
      post: /v1/api/list-beacon-block
      body: "*"
    - selector: api.API.ListUniqueBeaconBlockValues
      post: /v1/api/list-unique-beacon-block-values
      body: "*"
    - selector: api.API.CountBeaconBlock
      post: /v1/api/count-beacon-block
      body: "*"

    - selector: api.API.ListBeaconBadBlock
      post: /v1/api/list-beacon-bad-block
      body: "*"
    - selector: api.API.ListUniqueBeaconBadBlockValues
      post: /v1/api/list-unique-beacon-bad-block-values
      body: "*"
    - selector: api.API.CountBeaconBadBlock
      post: /v1/api/count-beacon-bad-block
      body: "*"

    - selector: api.API.ListBeaconBadBlob
      post: /v1/api/list-beacon-bad-blob
      body: "*"
    - selector: api.API.ListUniqueBeaconBadBlobValues
      post: /v1/api/list-unique-beacon-bad-blob-values
      body: "*"
    - selector: api.API.CountBeaconBadBlob
      post: /v1/api/count-beacon-bad-blob
      body: "*"

    - selector: api.API.ListExecutionBlockTrace
      post: /v1/api/list-execution-block-trace
      body: "*"
    - selector: api.API.ListUniqueExecutionBlockTraceValues
      post: /v1/api/list-unique-execution-block-trace-values
      body: "*"
    - selector: api.API.CountExecutionBlockTrace
      post: /v1/api/count-execution-block-trace
      body: "*"

    - selector: api.API.ListExecutionBadBlock
      post: /v1/api/list-execution-bad-block
      body: "*"
    - selector: api.API.ListUniqueExecutionBadBlockValues
      post: /v1/api/list-unique-execution-bad-block-values
      body: "*"
    - selector: api.API.CountExecutionBadBlock
      post: /v1/api/count-execution-bad-block
      body: "*"