server:
  addr: ":8085"
  metricsAddr: ":9091"
  pprofAddr: ":6060"
  gatewayAddr: ":7007"
  preStopSleepSeconds: 1
  ntpServer: time.google.com

  persistence:
    dsn: "file:/tmp/tracoor1.db?parseTime=True"
    driver_name: sqlite

  services:
    indexer:
      retention:
        beaconStates: 1m
        executionBlockTraces: 15m
        beaconBlocks: 1m
  ethereum:
    network: pepega-21
    config:
      repository: github.com/ethpandaops/pepega-devnets
      branch: main
      path: pepega-21
    tools:
      ncli:
        repository: github.com/ethpandaops/ncli
        branch: main
      lcli:
        repository: github.com/ethpandaops/lcli
        branch: main
      zcli:
        fork: uwotmate

agents:
  - name: example
    ethereum:
      features:
        fetchBeaconState: true
        fetchBeaconBlock: true
        fetchBeaconBadBlock: true
        fetchBeaconBadBlob: true
        fetchExecutionBlockTrace: true
        fetchExecutionBadBlock: true
      overrideNetworkName: example-network
      beacon:
        nodeAddress: http://example:5052
      execution:
        nodeAddress: http://example:8545

shared:
  metricsAddr: ":9091"
  logging: "debug"
  indexer:
    address: localhost:8085
  store:
    type: fs
    config:
      base_path: "/tmp/pepega"
