name: web-test

on:
  pull_request:
  workflow_dispatch:
    branches: [ '**' ]
permissions:
  contents: read
  checks: write

jobs:
  web-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Set up NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: web/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
