name: web-test

on:
  pull_request:
  workflow_dispatch:
    branches: [ '**' ]
permissions:
  contents: read
  checks: write

jobs:
  web-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: web/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
